import createConstants from "../utils/createConstant";

const types = createConstants(
  "FETCH_CAMPAIGNS_REQUEST",
  "FETCH_CAMPAIGNS_SUCCESS",
  "FETCH_CAMPAIGNS_FAILURE",
  "ON_JOIN_CAMPAIGN_REQUEST",
  "ON_JOIN_CAMPAIGN_SUCCESS",
  "ON_JOIN_CAMPAIGN_FAILURE",
  "ON_FETCH_CAMPAIGN_REQUEST",
  "ON_FETCH_CAMPAIGN_SUCCESS",
  "ON_FETCH_CAMPAIGN_FAILURE",
  "ON_UPDATE_SETTING_REQUEST",
  "ON_UPDATE_SETTING_SUCCESS",
  "ON_UPDATE_SETTING_FAILURE"
);

export { types };
